INSERT OR IGNORE INTO project_blocks(id,project_id,type,data,sort_order,visible) VALUES
('fasadof-system-brand','project-fasadof','SYSTEM_ITEM','{"number":"01","title":"BRAND","shortText":"Индивидуальный дизайн и brandbook.","detailText":"Визуальная система и брендбук формируют единый образ компании во всех цифровых точках контакта."}',1,1),
('fasadof-system-web','project-fasadof','SYSTEM_ITEM','{"number":"02","title":"WEB","shortText":"Публичный сайт и адаптивный интерфейс.","detailText":"Публичный сайт спроектирован как понятная точка входа в продукты и услуги компании на любых устройствах."}',2,1),
('fasadof-system-catalog','project-fasadof','SYSTEM_ITEM','{"number":"03","title":"CATALOG","shortText":"Каталог и карточки продукции.","detailText":"Структурированный каталог помогает изучать материалы и направления без перегрузки интерфейса."}',3,1),
('fasadof-system-admin','project-fasadof','SYSTEM_ITEM','{"number":"04","title":"ADMIN","shortText":"Управление контентом и внутренними процессами.","detailText":"Админ-панель объединяет управление контентом, обращениями и рабочими данными проекта."}',4,1),
('fasadof-system-max','project-fasadof','SYSTEM_ITEM','{"number":"05","title":"MAX","shortText":"Система бота и операционных уведомлений.","detailText":"Бот передаёт значимые события ответственным людям и связывает сайт с операционной работой."}',5,1),
('fasadof-system-social','project-fasadof','SYSTEM_ITEM','{"number":"06","title":"SOCIAL","shortText":"Оформление и ведение социальных каналов.","detailText":"Социальные каналы поддерживают общий визуальный язык и работают как часть единой digital-системы."}',6,1),
('fasadof-system-analytics','project-fasadof','SYSTEM_ITEM','{"number":"07","title":"ANALYTICS","shortText":"События и operational analytics.","detailText":"Система фиксирует реальные события и даёт основу для последующего анализа без выдуманных метрик."}',7,1),
('fasadof-system-infra','project-fasadof','SYSTEM_ITEM','{"number":"08","title":"INFRASTRUCTURE","shortText":"Production, persistence и развитие.","detailText":"Инфраструктура обеспечивает production-запуск, сохранность данных и возможность дальнейшего расширения."}',8,1);
