import { requireChatGPTUser } from "@/app/chatgpt-auth";
import { all, one } from "@/lib/platform";
import { AdminShell } from "@/components/admin/AdminShell";
import { WeatherCard } from "@/components/admin/WeatherCard";
async function metric(sql:string){try{return Number((await one<Record<string,unknown>>(sql))?.count??0)}catch{return 0}}
export default async function Dashboard(){
  const user=await requireChatGPTUser('/admin');
  const [leads,unread,open,works,tariffs,weatherSetting]=await Promise.all([metric("SELECT count(*) count FROM leads WHERE status='NEW'"),metric("SELECT count(*) count FROM messages WHERE sender_type='VISITOR' AND read_at IS NULL"),metric("SELECT count(*) count FROM conversations WHERE status!='CLOSED'"),metric("SELECT count(*) count FROM projects WHERE status='IN_PROGRESS'"),metric("SELECT count(*) count FROM tariffs WHERE is_visible=1"),one<{value:string}>("SELECT value FROM settings WHERE key='weather_city'").catch(()=>null)]);
  let dialogs:Record<string,unknown>[]=[];let activity:Record<string,unknown>[]=[];
  try{dialogs=await all("SELECT c.id,c.status,c.updated_at,m.text FROM conversations c LEFT JOIN messages m ON m.id=(SELECT id FROM messages WHERE conversation_id=c.id ORDER BY created_at DESC LIMIT 1) ORDER BY c.updated_at DESC LIMIT 5");activity=await all("SELECT action,entity_type,timestamp FROM audit_logs ORDER BY timestamp DESC LIMIT 6")}catch{}
  return <AdminShell active="/admin"><header className="admin-top"><div><span>Рабочее пространство</span><h1>Здравствуйте, {user.displayName}</h1></div><div className="admin-clock"><time>{new Intl.DateTimeFormat('ru-RU',{dateStyle:'full',timeStyle:'short',timeZone:'Europe/Moscow'}).format(new Date())}</time><span>Europe/Moscow</span></div></header><section className="metric-grid">{[['Новые заявки',leads],['Непрочитанные',unread],['Активные диалоги',open],['В работе',works],['Тарифы',tariffs]].map(([key,count])=><article key={String(key)}><span>{key}</span><strong>{count}</strong></article>)}</section><section className="admin-grid"><article className="admin-card admin-card--wide"><div className="card-head"><h2>Последние диалоги</h2><a href="/admin/dialogs">Все диалоги →</a></div>{dialogs.length?dialogs.map(dialog=><p key={String(dialog.id)}><b>{String(dialog.status)}</b> {String(dialog.text??'Нет сообщений')}</p>):<div className="empty">Нет новых диалогов.</div>}</article><WeatherCard initialCity={weatherSetting?.value||'Воронеж'}/><article className="admin-card"><h2>Последние действия</h2>{activity.length?activity.map((item,index)=><p key={index}>{String(item.action)} · {String(item.entity_type)}</p>):<div className="empty">Действий пока нет.</div>}</article><article className="admin-card"><h2>Быстрые действия</h2><div className="quick"><a href="/admin/works">+ Новая работа</a><a href="/admin/tariffs">+ Новый тариф</a><a href="/admin/dialogs">Открыть диалоги</a><a href="/">Открыть сайт ↗</a></div></article></section></AdminShell>
}
