import bcrypt from "bcryptjs";
import { readAdmin } from "@/lib/admin-auth";
import { all,clean,database,id,json,recordEvent } from "@/lib/platform";
async function owner(){const identity=await readAdmin();return identity?.isOwner?identity:null}
const permissions=(value:unknown)=>Array.isArray(value)?value.map(item=>clean(item,100)).filter(Boolean):[];
export async function GET(){if(!await owner())return json({error:'Только владелец может управлять командой.'},403);return json({users:await all("SELECT u.id,u.email,u.name,u.active,u.role_id,r.name role,r.permissions,u.updated_at FROM users u JOIN roles r ON r.id=u.role_id ORDER BY u.created_at"),roles:await all("SELECT id,name,permissions,is_system,updated_at FROM roles ORDER BY name")})}
export async function POST(request:Request){const admin=await owner();if(!admin)return json({error:'Только владелец может управлять командой.'},403);const body=await request.json().catch(()=>({})) as Record<string,unknown>,kind=clean(body.kind,20);if(kind==='role'){const name=clean(body.name,100),items=permissions(body.permissions);if(!name)return json({error:'Название роли обязательно.'},400);const roleId=id();await database().prepare("INSERT INTO roles(id,name,permissions) VALUES(?,?,?)").bind(roleId,name,JSON.stringify(items)).run();await recordEvent('ROLE_CREATED','role',roleId,{name,permissions:items},admin.email);return json({ok:true,id:roleId},201)}if(kind==='user'){const email=clean(body.email,200).toLowerCase(),name=clean(body.name,120),password=String(body.password||'').slice(0,200),roleId=clean(body.roleId,80);if(!email||!name||password.length<8||!roleId)return json({error:'Имя, email, роль и пароль от 8 символов обязательны.'},400);const userId=id(),hash=bcrypt.hashSync(password,12);await database().prepare("INSERT INTO users(id,email,name,password_hash,role_id) VALUES(?,?,?,?,?)").bind(userId,email,name,hash,roleId).run();await recordEvent('EMPLOYEE_CREATED','user',userId,{email,name,roleId},admin.email);return json({ok:true,id:userId},201)}return json({error:'Неизвестная операция.'},400)}
export async function PATCH(request:Request){const admin=await owner();if(!admin)return json({error:'Только владелец может управлять командой.'},403);const body=await request.json().catch(()=>({})) as Record<string,unknown>,kind=clean(body.kind,20),entityId=clean(body.id,80);if(kind==='role'){await database().prepare("UPDATE roles SET name=?,permissions=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND is_system=0").bind(clean(body.name,100),JSON.stringify(permissions(body.permissions)),entityId).run()}else if(kind==='user'){await database().prepare("UPDATE users SET name=?,role_id=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(clean(body.name,120),clean(body.roleId,80),body.active===false?0:1,entityId).run()}else return json({error:'Неизвестная операция.'},400);await recordEvent(`${kind.toUpperCase()}_UPDATED`,kind,entityId,{},admin.email);return json({ok:true})}
export async function DELETE(request:Request){const admin=await owner();if(!admin)return json({error:'Только владелец может управлять командой.'},403);const body=await request.json().catch(()=>({})) as Record<string,unknown>,kind=clean(body.kind,20),entityId=clean(body.id,80);if(kind==='user')await database().prepare("DELETE FROM users WHERE id=?").bind(entityId).run();else if(kind==='role'){const used=await database().prepare("SELECT count(*) count FROM users WHERE role_id=?").bind(entityId).first<{count:number}>();if(Number(used?.count))return json({error:'Роль назначена сотрудникам.'},409);await database().prepare("DELETE FROM roles WHERE id=? AND is_system=0").bind(entityId).run()}else return json({error:'Неизвестная операция.'},400);await recordEvent(`${kind.toUpperCase()}_DELETED`,kind,entityId,{},admin.email);return json({ok:true})}
