"use client";
import { FormEvent,useEffect,useRef,useState } from "react";
type Message={id:string;senderType:string;text:string;createdAt:string};
type ChatData={conversation?:{id:string;status:string};messages?:Message[];conversationId?:string;message?:Message;error?:string};
export function ChatWidget(){
 const [open,setOpen]=useState(false),[conversationId,setConversationId]=useState(''),[status,setStatus]=useState('OPEN'),[messages,setMessages]=useState<Message[]>([]),[notice,setNotice]=useState(''); const panel=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(open)fetch('/api/chat').then(r=>r.json() as Promise<ChatData>).then(d=>{setConversationId(d.conversation?.id||'');setStatus(d.conversation?.status||'OPEN');setMessages(d.messages||[])}).catch(()=>setNotice('Не удалось загрузить чат.'))},[open]);
 useEffect(()=>{if(!open)return;const esc=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};addEventListener('keydown',esc);panel.current?.focus();return()=>removeEventListener('keydown',esc)},[open]);
 async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;const input=new FormData(f).get('text');const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({conversationId,text:input})});const d=await r.json() as ChatData;if(r.ok&&d.conversationId&&d.message){setConversationId(d.conversationId);setMessages(v=>[...v,d.message!]);f.reset()}else setNotice(d.error||'Не удалось отправить сообщение.')}
 async function close(){await fetch('/api/chat',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({conversationId})});setStatus('CLOSED')}
 async function rate(score:number){await fetch('/api/chat',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({conversationId,score})});setNotice('Спасибо за оценку.')}
 return <><button className="chat-fab" onClick={()=>setOpen(true)} aria-label="Открыть чат">Чат <span>↗</span></button>{open&&<div className="chat-panel" ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Чат OnikArt"><header><div><b>ONIKART.</b><span>Оставьте сообщение — отвечу позже.</span></div><button onClick={()=>setOpen(false)} aria-label="Закрыть">×</button></header><div className="chat-messages">{messages.length?messages.map(m=><p className={m.senderType==='VISITOR'?'mine':''} key={m.id}>{m.text}</p>):<div className="empty">Напишите о задаче. История сохранится на этом устройстве.</div>}{status==='CLOSED'&&<div className="rating"><b>Как прошёл диалог?</b><div>{[1,2,3,4,5].map(n=><button key={n} onClick={()=>rate(n)} aria-label={`${n} из 5`}>★</button>)}</div></div>}</div>{status!=='CLOSED'&&<form onSubmit={send}><input name="text" required maxLength={2000} placeholder="Сообщение" aria-label="Сообщение"/><button>↑</button></form>}{conversationId&&status!=='CLOSED'&&<button className="chat-close" onClick={close}>Завершить диалог</button>}{notice&&<small role="status">{notice}</small>}</div>}</>}
