import { boolean, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

const stamp = { createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() };
export const settings = pgTable("settings", { key: text("key").primaryKey(), value: text("value").notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const leads = pgTable("leads", { id: text("id").primaryKey(), name: text("name").notNull(), phone: text("phone").notNull(), message: text("message"), source: text("source"), utm: text("utm"), page: text("page"), status: text("status").notNull().default("NEW"), notes: text("notes"), ...stamp }, table => [index("leads_status_created_idx").on(table.status, table.createdAt)]);
export const tariffs = pgTable("tariffs", { id: text("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull(), eyebrow: text("eyebrow"), description: text("description").notNull(), priceMode: text("price_mode").notNull(), priceFrom: integer("price_from"), features: jsonb("features").$type<string[]>().notNull().default([]), highlighted: boolean("highlighted").notNull().default(false), badge: text("badge"), cta: text("cta").notNull(), order: integer("sort_order").notNull().default(0), isVisible: boolean("is_visible").notNull().default(true), ...stamp }, table => [uniqueIndex("tariffs_slug_uidx").on(table.slug), index("tariffs_visible_order_idx").on(table.isVisible, table.order)]);
export const services = pgTable("services", { id: text("id").primaryKey(), number: text("number").notNull(), kicker: text("kicker").notNull(), title: text("title").notNull(), slug: text("slug").notNull(), description: text("description").notNull(), items: jsonb("items").$type<string[]>().notNull().default([]), order: integer("sort_order").notNull().default(0), isVisible: boolean("is_visible").notNull().default(true), ...stamp }, table => [uniqueIndex("services_slug_uidx").on(table.slug), index("services_visible_order_idx").on(table.isVisible, table.order)]);
export const roles = pgTable("roles", { id: text("id").primaryKey(), name: text("name").notNull(), permissions: jsonb("permissions").$type<string[]>().notNull().default([]), isSystem: boolean("is_system").notNull().default(false), ...stamp }, table => [uniqueIndex("roles_name_uidx").on(table.name)]);
export const users = pgTable("users", { id: text("id").primaryKey(), email: text("email").notNull(), name: text("name").notNull(), passwordHash: text("password_hash").notNull(), roleId: text("role_id").notNull().references(() => roles.id, { onDelete: "restrict" }), active: boolean("active").notNull().default(true), ...stamp }, table => [uniqueIndex("users_email_uidx").on(table.email), index("users_role_idx").on(table.roleId)]);
export const projects = pgTable("projects", { id: text("id").primaryKey(), title: text("title").notNull(), slug: text("slug").notNull(), subtitle: text("subtitle"), shortDescription: text("short_description").notNull(), status: text("status").notNull().default("IN_PROGRESS"), published: boolean("published").notNull().default(false), featured: boolean("featured").notNull().default(false), featuredOrder: integer("featured_order").notNull().default(0), cover: text("cover"), serviceTags: jsonb("service_tags").$type<string[]>().notNull().default([]), seoTitle: text("seo_title"), seoDescription: text("seo_description"), ogImage: text("og_image"), ...stamp }, table => [uniqueIndex("projects_slug_uidx").on(table.slug), index("projects_public_idx").on(table.published, table.featured, table.featuredOrder)]);
export const projectLinks = pgTable("project_links", { id: text("id").primaryKey(), projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), label: text("label").notNull(), description: text("description"), url: text("url").notNull(), order: integer("sort_order").notNull().default(0), visible: boolean("visible").notNull().default(true) }, table => [index("project_links_project_order_idx").on(table.projectId, table.order)]);
export const projectBlocks = pgTable("project_blocks", { id: text("id").primaryKey(), projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), type: text("type").notNull(), data: jsonb("data").$type<Record<string, unknown>>().notNull().default({}), order: integer("sort_order").notNull().default(0), visible: boolean("visible").notNull().default(true) }, table => [index("project_blocks_project_type_order_idx").on(table.projectId, table.type, table.order)]);
export const projectMedia = pgTable("project_media", { id: text("id").primaryKey(), projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), deviceType: text("device_type").notNull(), mediaUrl: text("media_url").notNull(), alt: text("alt").notNull().default(""), caption: text("caption"), order: integer("sort_order").notNull().default(0), visible: boolean("visible").notNull().default(true) }, table => [index("project_media_project_order_idx").on(table.projectId, table.order)]);
export const conversations = pgTable("conversations", { id: text("id").primaryKey(), visitorId: text("visitor_id").notNull(), status: text("status").notNull().default("NEW"), ...stamp, closedAt: timestamp("closed_at", { withTimezone: true }) }, table => [index("conversations_visitor_updated_idx").on(table.visitorId, table.updatedAt), index("conversations_status_idx").on(table.status)]);
export const messages = pgTable("messages", { id: text("id").primaryKey(), conversationId: text("conversation_id").notNull().references(() => conversations.id, { onDelete: "cascade" }), senderType: text("sender_type").notNull(), text: text("text").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), readAt: timestamp("read_at", { withTimezone: true }) }, table => [index("messages_conversation_created_idx").on(table.conversationId, table.createdAt), index("messages_unread_idx").on(table.senderType, table.readAt)]);
export const ratings = pgTable("ratings", { id: text("id").primaryKey(), conversationId: text("conversation_id").notNull().references(() => conversations.id, { onDelete: "cascade" }), score: integer("score").notNull(), comment: text("comment"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, table => [uniqueIndex("ratings_conversation_uidx").on(table.conversationId)]);
export const auditLogs = pgTable("audit_logs", { id: text("id").primaryKey(), actor: text("actor").notNull(), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id"), metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}), timestamp: timestamp("timestamp", { withTimezone: true }).notNull().defaultNow() }, table => [index("audit_logs_timestamp_idx").on(table.timestamp), index("audit_logs_entity_idx").on(table.entityType, table.entityId)]);
export const notificationEvents = pgTable("notification_events", { id: text("id").primaryKey(), category: text("category").notNull(), event: text("event").notNull(), entityType: text("entity_type"), entityId: text("entity_id"), payload: jsonb("payload").$type<Record<string, unknown>>().notNull().default({}), status: text("status").notNull().default("PENDING"), attempts: integer("attempts").notNull().default(0), error: text("error"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), sentAt: timestamp("sent_at", { withTimezone: true }) }, table => [index("notification_events_status_created_idx").on(table.status, table.createdAt)]);
