import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

const stamp = { createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"), updatedAt: text("updated_at").notNull().default("CURRENT_TIMESTAMP") };
export const settings = sqliteTable("settings", { key: text("key").primaryKey(), value: text("value").notNull(), updatedAt: text("updated_at").notNull().default("CURRENT_TIMESTAMP") });
export const leads = sqliteTable("leads", { id: text("id").primaryKey(), name: text("name").notNull(), phone: text("phone").notNull(), message: text("message"), source: text("source"), utm: text("utm"), page: text("page"), status: text("status").notNull().default("NEW"), notes: text("notes"), ...stamp });
export const tariffs = sqliteTable("tariffs", { id: text("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull().unique(), eyebrow: text("eyebrow"), description: text("description").notNull(), priceMode: text("price_mode").notNull(), priceFrom: integer("price_from"), features: text("features").notNull().default("[]"), highlighted: integer("highlighted", { mode: "boolean" }).notNull().default(false), badge: text("badge"), cta: text("cta").notNull(), order: integer("sort_order").notNull().default(0), isVisible: integer("is_visible", { mode: "boolean" }).notNull().default(true), ...stamp });
export const services = sqliteTable("services", { id: text("id").primaryKey(), number: text("number").notNull(), kicker: text("kicker").notNull(), title: text("title").notNull(), slug: text("slug").notNull().unique(), description: text("description").notNull(), items: text("items").notNull().default("[]"), order: integer("sort_order").notNull().default(0), isVisible: integer("is_visible", { mode: "boolean" }).notNull().default(true), ...stamp });
export const roles = sqliteTable("roles", { id:text("id").primaryKey(), name:text("name").notNull().unique(), permissions:text("permissions").notNull().default("[]"), isSystem:integer("is_system",{mode:"boolean"}).notNull().default(false), ...stamp });
export const users = sqliteTable("users", { id:text("id").primaryKey(), email:text("email").notNull().unique(), name:text("name").notNull(), passwordHash:text("password_hash").notNull(), roleId:text("role_id").notNull(), active:integer("active",{mode:"boolean"}).notNull().default(true), ...stamp });
export const projects = sqliteTable("projects", { id: text("id").primaryKey(), title: text("title").notNull(), slug: text("slug").notNull().unique(), subtitle: text("subtitle"), shortDescription: text("short_description").notNull(), status: text("status").notNull().default("IN_PROGRESS"), published: integer("published", { mode: "boolean" }).notNull().default(false), featured: integer("featured", { mode: "boolean" }).notNull().default(false), featuredOrder: integer("featured_order").notNull().default(0), cover: text("cover"), serviceTags: text("service_tags").notNull().default("[]"), seoTitle: text("seo_title"), seoDescription: text("seo_description"), ogImage: text("og_image"), ...stamp });
export const projectLinks = sqliteTable("project_links", { id: text("id").primaryKey(), projectId: text("project_id").notNull(), label: text("label").notNull(), description: text("description"), url: text("url").notNull(), order: integer("sort_order").notNull().default(0), visible: integer("visible", { mode: "boolean" }).notNull().default(true) });
export const projectBlocks = sqliteTable("project_blocks", { id: text("id").primaryKey(), projectId: text("project_id").notNull(), type: text("type").notNull(), data: text("data").notNull().default("{}"), order: integer("sort_order").notNull().default(0), visible: integer("visible", { mode: "boolean" }).notNull().default(true) });
export const projectMedia = sqliteTable("project_media", { id: text("id").primaryKey(), projectId: text("project_id").notNull(), deviceType: text("device_type").notNull(), mediaUrl: text("media_url").notNull(), alt: text("alt").notNull().default(""), caption: text("caption"), order: integer("sort_order").notNull().default(0), visible: integer("visible", { mode: "boolean" }).notNull().default(true) });
export const conversations = sqliteTable("conversations", { id: text("id").primaryKey(), visitorId: text("visitor_id").notNull(), status: text("status").notNull().default("NEW"), ...stamp, closedAt: text("closed_at") });
export const messages = sqliteTable("messages", { id: text("id").primaryKey(), conversationId: text("conversation_id").notNull(), senderType: text("sender_type").notNull(), text: text("text").notNull(), createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"), readAt: text("read_at") });
export const ratings = sqliteTable("ratings", { id: text("id").primaryKey(), conversationId: text("conversation_id").notNull().unique(), score: integer("score").notNull(), comment: text("comment"), createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP") });
export const auditLogs = sqliteTable("audit_logs", { id: text("id").primaryKey(), actor: text("actor").notNull(), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id"), metadata: text("metadata").notNull().default("{}"), timestamp: text("timestamp").notNull().default("CURRENT_TIMESTAMP") });
export const notificationEvents = sqliteTable("notification_events", { id: text("id").primaryKey(), category: text("category").notNull(), event: text("event").notNull(), entityType: text("entity_type"), entityId: text("entity_id"), payload: text("payload").notNull().default("{}"), status: text("status").notNull().default("PENDING"), attempts: integer("attempts").notNull().default(0), error: text("error"), createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"), sentAt: text("sent_at") });
