"use client";
import { FormEvent, useMemo, useState } from "react";
import { TeamWorkspace } from "@/components/admin/TeamWorkspace";

type Row=Record<string,unknown>;
const copy:Record<string,string>={leads:"Заявки с публичной формы сохраняются здесь.",dialogs:"Диалоги сайта: ответы, закрытие и оценки.",works:"Создавайте, редактируйте и публикуйте работы.",tariffs:"Управляйте ценой, составом, порядком и видимостью тарифов.",services:"Управляйте публичным списком услуг.",ratings:"Реальные оценки завершённых диалогов.",analytics:"Только реальные показатели после накопления событий.",content:"Главные тексты и публичный контент.",notifications:"Очередь Telegram: отправлено, ошибка, повтор.",integrations:"Статус Telegram и тестовое уведомление.",settings:"Контакты, социальные ссылки, погода и SEO."};
const editable=new Set(["works","tariffs","services"]);
const value=(row:Row,key:string)=>String(row[key]??"");
function arrayField(value:unknown):unknown[]{
  if(Array.isArray(value))return value;
  if(typeof value==='string')try{const parsed:unknown=JSON.parse(value);return Array.isArray(parsed)?parsed:[]}catch{return []}
  return [];
}
function initial(section:string,row?:Row):Row{
  if(section==='works')return {title:value(row??{},'title'),description:value(row??{},'short_description'),seoTitle:value(row??{},'seo_title'),seoDescription:value(row??{},'seo_description'),status:value(row??{},'status')||'IN_PROGRESS',published:Boolean(row?.published),featured:Boolean(row?.featured),order:Number(row?.featured_order)||0,tags:arrayField(row?.service_tags).map(String).join('\n'),systemItems:arrayField(row?.system_items).map(item=>{const block=item as {title?:string;shortText?:string;detailText?:string};return [block.title,block.shortText,block.detailText].join('|')}).join('\n')};
  if(section==='tariffs')return {name:value(row??{},'name'),eyebrow:value(row??{},'eyebrow'),description:value(row??{},'description'),priceMode:value(row??{},'price_mode')||'FROM',priceFrom:value(row??{},'price_from'),features:(()=>{try{return JSON.parse(value(row??{},'features')).join('\n')}catch{return ''}})(),cta:value(row??{},'cta')||'Обсудить проект',order:Number(row?.sort_order)||0,isVisible:row?Boolean(row.is_visible):true};
  return {number:value(row??{},'number')||'01',kicker:value(row??{},'kicker')||'SERVICE',title:value(row??{},'title'),description:value(row??{},'description'),items:(()=>{try{return JSON.parse(value(row??{},'items')).join('\n')}catch{return ''}})(),order:Number(row?.sort_order)||0,isVisible:row?Boolean(row.is_visible):true};
}

export function AdminWorkspace({section,initialRows}:{section:string;initialRows:Row[]}){
  const [rows,setRows]=useState(initialRows),[query,setQuery]=useState(''),[editing,setEditing]=useState<Row|null>(null),[form,setForm]=useState<Row>(()=>initial(section)),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Row|null>(null),[messages,setMessages]=useState<Row[]>([]);
  const filtered=useMemo(()=>rows.filter(row=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase())),[rows,query]);
  async function refresh(resource=section){const response=await fetch(`/api/admin/resources?resource=${resource}`,{cache:'no-store'});const data=await response.json() as {rows?:Row[];error?:string};if(!response.ok)throw new Error(data.error||'Не удалось обновить данные.');setRows(data.rows??[])}
  function openEditor(row?:Row){setEditing(row??{});setForm(initial(section,row));setNotice('')}
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setNotice('');try{const response=await fetch('/api/admin/resources',{method:editing?.id?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(editing?.id?{resource:section,id:editing.id,data:form}:{resource:section,data:form})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||'Сохранение не выполнено.');await refresh();setEditing(null);setNotice('Изменения сохранены в базе данных.')}catch(error){setNotice(error instanceof Error?error.message:'Сохранение не выполнено.')}finally{setBusy(false)}}
  async function remove(row:Row){if(!confirm(`Удалить «${value(row,'title')||value(row,'name')||value(row,'id')}»?`))return;setBusy(true);try{const response=await fetch('/api/admin/resources',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({resource:section,id:row.id})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||'Удаление не выполнено.');await refresh();setNotice('Запись удалена из базы данных.')}catch(error){setNotice(error instanceof Error?error.message:'Удаление не выполнено.')}finally{setBusy(false)}}
  async function toggle(row:Row,key:string){const next=initial(section,row);next[key]=!Boolean(row[key==='isVisible'?'is_visible':key]);setEditing(row);setForm(next);setBusy(true);try{const response=await fetch('/api/admin/resources',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({resource:section,id:row.id,data:next})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||'Изменение не выполнено.');await refresh();setEditing(null);setNotice('Статус сохранён.')}catch(error){setNotice(error instanceof Error?error.message:'Изменение не выполнено.')}finally{setBusy(false)}}
  async function openDialog(row:Row){setSelected(row);const response=await fetch(`/api/admin/messages?conversationId=${encodeURIComponent(value(row,'id'))}`,{cache:'no-store'});const data=await response.json() as {messages?:Row[]};setMessages(data.messages??[])}
  async function dialogAction(method:'POST'|'PATCH',data:Row){setBusy(true);setNotice('');try{const response=await fetch('/api/admin/dialogs',{method,headers:{'content-type':'application/json'},body:JSON.stringify(data)});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||'Операция не выполнена.');await openDialog(selected!);setNotice('Диалог обновлён.')}catch(error){setNotice(error instanceof Error?error.message:'Операция не выполнена.')}finally{setBusy(false)}}
  async function telegram(method:'GET'|'POST'){setBusy(true);setNotice('');try{const response=await fetch('/api/admin/telegram',{method});const data=await response.json() as {error?:string;bot?:string};if(!response.ok)throw new Error(data.error||'Проверка не выполнена.');setNotice(method==='GET'?`Bot API доступен${data.bot?` · @${data.bot}`:''}.`:'Тестовое сообщение отправлено.')}catch(error){setNotice(error instanceof Error?error.message:'Проверка не выполнена.')}finally{setBusy(false)}}
  async function uploadMedia(row:Row,file:File){setBusy(true);setNotice('');try{const body=new FormData();body.set('projectId',String(row.id));body.set('file',file);body.set('alt',String(row.title??''));const response=await fetch('/api/admin/media',{method:'POST',body});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||'Загрузка не выполнена.');await refresh();setNotice('Изображение сохранено в постоянном хранилище.')}catch(error){setNotice(error instanceof Error?error.message:'Загрузка не выполнена.')}finally{setBusy(false)}}
  if(section==='team')return <TeamWorkspace/>;
  return <section className="admin-workspace"><div className="workspace-toolbar"><p>{copy[section]}</p>{['leads','dialogs','works','tariffs','services','ratings'].includes(section)&&<input aria-label="Поиск" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Поиск"/>}{editable.has(section)&&<button type="button" onClick={()=>openEditor()}>+ Добавить</button>}</div>
    {notice&&<p className="admin-notice" role="status">{notice}</p>}
    {section==='integrations'&&<article className="admin-card"><h2>Telegram</h2><p>Токен хранится только в окружении сервера.</p><div className="admin-actions"><button disabled={busy} onClick={()=>telegram('GET')}>Проверить Bot API</button><button disabled={busy} onClick={()=>telegram('POST')}>Отправить тест</button></div></article>}
    {section==='settings'&&<Settings onSaved={message=>setNotice(message)}/>} 
    {editing&&section==='works'&&<div className="admin-editor"><Field label="SEO title" name="seoTitle" form={form} setForm={setForm}/><Field label="SEO description" name="seoDescription" form={form} setForm={setForm} area/><Field label="Порядок" name="order" type="number" form={form} setForm={setForm}/><Field label="Системные пункты — НАЗВАНИЕ|КРАТКО|ПОДРОБНО, по одному в строке" name="systemItems" form={form} setForm={setForm} area/></div>}
    {editing&&editable.has(section)&&<ResourceForm section={section} form={form} setForm={setForm} busy={busy} onSubmit={save} onCancel={()=>setEditing(null)}/>} 
    {selected&&section==='dialogs'&&<DialogPanel selected={selected} messages={messages} busy={busy} onClose={()=>setSelected(null)} onAction={dialogAction}/>} 
    {filtered.length?<div className="data-list">{filtered.map((row,index)=><article key={String(row.id??index)}><div><b>{value(row,'title')||value(row,'name')||value(row,'event')||value(row,'id')}</b><span>{value(row,'status')||value(row,'score')||value(row,'updated_at')}</span></div><div className="row-actions">{editable.has(section)&&<><button onClick={()=>openEditor(row)}>Изменить</button>{section==='works'&&<><button onClick={()=>toggle(row,'published')}>{row.published?'Скрыть':'Опубликовать'}</button><a href={`/work/${encodeURIComponent(value(row,'slug'))}?preview=1`} target="_blank" rel="noopener noreferrer">Предпросмотр</a><label>Изображение<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={event=>{const file=event.currentTarget.files?.[0];if(file)void uploadMedia(row,file);event.currentTarget.value=''}}/></label></>}{['tariffs','services'].includes(section)&&<button onClick={()=>toggle(row,'isVisible')}>{row.is_visible?'Скрыть':'Показать'}</button>}<button className="danger" onClick={()=>remove(row)}>Удалить</button></>}{section==='dialogs'&&<button onClick={()=>openDialog(row)}>Открыть →</button>}{!editable.has(section)&&section!=='dialogs'&&<span>{value(row,'phone')||value(row,'category')||''}</span>}</div></article>)}</div>:!['settings','integrations','analytics','content'].includes(section)&&<div className="empty empty--large">Данных пока нет.</div>}
  </section>
}

function Field({label,name,form,setForm,area=false,type='text'}:{label:string;name:string;form:Row;setForm:(row:Row)=>void;area?:boolean;type?:string}){const props={name,value:String(form[name]??''),onChange:(event:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>setForm({...form,[name]:event.target.value}),required:['title','name','description'].includes(name)};return <label>{label}{area?<textarea {...props} rows={4}/>:<input {...props} type={type}/>}</label>}
function ResourceForm({section,form,setForm,busy,onSubmit,onCancel}:{section:string;form:Row;setForm:(row:Row)=>void;busy:boolean;onSubmit:(event:FormEvent)=>void;onCancel:()=>void}){return <form className="admin-editor" onSubmit={onSubmit}><div className="card-head"><h2>Редактор</h2><button type="button" onClick={onCancel}>Закрыть</button></div>{section==='tariffs'?<><Field label="Название" name="name" form={form} setForm={setForm}/><Field label="Номер" name="eyebrow" form={form} setForm={setForm}/><Field label="Описание" name="description" form={form} setForm={setForm} area/><label>Режим цены<select value={String(form.priceMode)} onChange={event=>setForm({...form,priceMode:event.target.value})}><option value="FROM">От</option><option value="INDIVIDUAL">Индивидуально</option></select></label><Field label="Цена" name="priceFrom" type="number" form={form} setForm={setForm}/><Field label="Пункты — по одному в строке" name="features" form={form} setForm={setForm} area/><label className="check"><input type="checkbox" checked={Boolean(form.isVisible)} onChange={event=>setForm({...form,isVisible:event.target.checked})}/>Показывать на сайте</label></>:section==='services'?<><Field label="Номер" name="number" form={form} setForm={setForm}/><Field label="Kicker" name="kicker" form={form} setForm={setForm}/><Field label="Название" name="title" form={form} setForm={setForm}/><Field label="Описание" name="description" form={form} setForm={setForm} area/><Field label="Пункты — по одному в строке" name="items" form={form} setForm={setForm} area/><label className="check"><input type="checkbox" checked={Boolean(form.isVisible)} onChange={event=>setForm({...form,isVisible:event.target.checked})}/>Показывать на сайте</label></>:<><Field label="Название" name="title" form={form} setForm={setForm}/><Field label="Описание" name="description" form={form} setForm={setForm} area/><label>Статус<select value={String(form.status)} onChange={event=>setForm({...form,status:event.target.value})}><option value="IN_PROGRESS">В работе</option><option value="DONE">Завершено</option></select></label><Field label="Теги — по одному в строке" name="tags" form={form} setForm={setForm} area/><label className="check"><input type="checkbox" checked={Boolean(form.published)} onChange={event=>setForm({...form,published:event.target.checked})}/>Опубликовано</label><label className="check"><input type="checkbox" checked={Boolean(form.featured)} onChange={event=>setForm({...form,featured:event.target.checked})}/>Показывать на главной</label></>}<div className="admin-actions"><button disabled={busy} type="submit">{busy?'Сохраняем…':'Сохранить'}</button><button type="button" onClick={onCancel}>Отмена</button></div></form>}
function DialogPanel({selected,messages,busy,onClose,onAction}:{selected:Row;messages:Row[];busy:boolean;onClose:()=>void;onAction:(method:'POST'|'PATCH',data:Row)=>void}){const [reply,setReply]=useState('');return <section className="admin-editor"><div className="card-head"><h2>Диалог {String(selected.id).slice(0,8)}</h2><button onClick={onClose}>Закрыть панель</button></div><div className="admin-messages">{messages.map(row=><p key={String(row.id)} className={row.senderType==='ADMIN'?'mine':''}><b>{String(row.senderType)}</b>{String(row.text)}</p>)}</div><form onSubmit={event=>{event.preventDefault();if(!reply.trim())return;onAction('POST',{conversationId:selected.id,text:reply});setReply('')}}><label>Ответ<textarea value={reply} onChange={event=>setReply(event.target.value)} required/></label><button disabled={busy}>Ответить</button></form><button disabled={busy} onClick={()=>onAction('PATCH',{conversationId:selected.id,status:selected.status==='CLOSED'?'OPEN':'CLOSED'})}>{selected.status==='CLOSED'?'Открыть снова':'Завершить диалог'}</button></section>}
function Settings({onSaved}:{onSaved:(message:string)=>void}){const [key,setKey]=useState('weather_city'),[value,setValue]=useState('Воронеж'),[busy,setBusy]=useState(false);async function save(event:FormEvent){event.preventDefault();setBusy(true);const response=await fetch('/api/admin/resources',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({resource:'settings',id:key,data:{key,value}})});const data=await response.json() as {error?:string};onSaved(response.ok?'Настройка сохранена в базе данных.':data.error||'Ошибка сохранения.');setBusy(false)}return <form className="admin-editor" onSubmit={save}><h2>Настройка</h2><label>Ключ<input value={key} onChange={event=>setKey(event.target.value)} required/></label><label>Значение<textarea value={value} onChange={event=>setValue(event.target.value)} required/></label><button disabled={busy}>{busy?'Сохраняем…':'Сохранить'}</button></form>}
