import pg from "pg";

const url=process.env.DATABASE_URL?.trim();if(!url)throw new Error("DATABASE_URL is required for db:seed");
const pool=new pg.Pool({connectionString:url,max:2});
const services=[
['service-foundation','01','DIGITAL FOUNDATION','Цифровой фундамент','digital-foundation','Фундамент продукта: позиционирование, структура, визуальная система и интерфейс.',['Структура','UI / UX','Визуальная система','Прототипирование','Контент-архитектура'],1],
['service-web','02','WEB & SYSTEMS','Веб и системы','web-systems','Сайты и внутренние инструменты, которые не заканчиваются красивой главной страницей.',['Сайты','Каталоги','Frontend','Backend','Базы данных','Админ-панели','Формы и заявки'],2],
['service-automation','03','AUTOMATION & GROWTH','Автоматизация и рост','automation-growth','Интеграции и автоматизация процессов, которые помогают системе работать после запуска.',['Аналитика','API','Интеграции','AI','Автоматизация','Production'],3],
['service-social','04','SOCIAL & CONTENT','Социальные каналы','social-content','Создание и оформление соцсетей, редизайн существующих аккаунтов, контент-система, ведение и связь с digital-экосистемой.',['Создание соцсетей','Оформление','Редизайн','Контент','Ведение','Сопровождение'],4],
['service-consulting','05','CONSULTING','Консультация','consulting','Разбор задачи, текущей цифровой системы и возможных следующих шагов.',['Digital-аудит','Аудит сайта','Бизнес-процессы','Roadmap','Выбор инструментов'],5],
['service-support','06','SUPPORT / LONG-TERM','Сопровождение и развитие','support','После запуска продолжаю развитие проекта: поддержка, новые функции, аналитика, интеграции и автоматизация.',['Поддержка','Обновления','Новые функции','Аналитика','Интеграции','Контент'],6],
];
const tariffs=[
['tariff-start','DIGITAL START','digital-start','01','Сильная digital-точка входа для небольшого бизнеса или специалиста.','FROM',['Анализ задачи','Структура и дизайн','Адаптивная разработка','Форма заявки','Базовое SEO и аналитика','Production launch'],1],
['tariff-business','BUSINESS SYSTEM','business-system','02','Для бизнеса, которому нужен не просто сайт, а рабочая система.','FROM',['Всё из Digital Start','Дополнительные страницы','Каталог и база данных','Админ-панель','Заявки и события','Интеграции'],2],
['tariff-digital','DIGITAL BUSINESS','digital-business','03','Комплексная цифровая инфраструктура бизнеса.','FROM',['Стратегия и брендинг','Website, backend и database','Custom admin и роли','Bots и automation','Social ecosystem','Production infrastructure'],3],
['tariff-support','ДАЛЬНЕЙШЕЕ СОТРУДНИЧЕСТВО','support','04','Поддержка и развитие уже запущенной системы.','INDIVIDUAL',['Техническая поддержка','Новые функции','Аналитика','Интеграции','Автоматизация','Развитие digital-системы'],4],
];
const system=[['BRAND','Индивидуальный дизайн и brandbook.','Визуальная система и брендбук формируют единый образ компании во всех цифровых точках контакта.'],['WEB','Публичный сайт и адаптивный интерфейс.','Публичный сайт спроектирован как понятная точка входа в продукты и услуги компании на любых устройствах.'],['CATALOG','Каталог и карточки продукции.','Структурированный каталог помогает изучать материалы и направления без перегрузки интерфейса.'],['ADMIN','Управление контентом и внутренними процессами.','Админ-панель объединяет управление контентом, обращениями и рабочими данными проекта.'],['MAX','Система бота и операционных уведомлений.','Бот передаёт значимые события ответственным людям и связывает сайт с операционной работой.'],['SOCIAL','Оформление и ведение социальных каналов.','Социальные каналы поддерживают общий визуальный язык и работают как часть единой digital-системы.'],['ANALYTICS','События и operational analytics.','Система фиксирует реальные события и даёт основу для последующего анализа без выдуманных метрик.'],['INFRASTRUCTURE','Production, persistence и развитие.','Инфраструктура обеспечивает production-запуск, сохранность данных и возможность дальнейшего расширения.']];
const client=await pool.connect();try{await client.query('BEGIN');for(const row of services)await client.query('INSERT INTO services(id,number,kicker,title,slug,description,items,sort_order,is_visible) VALUES($1,$2,$3,$4,$5,$6,$7,$8,true) ON CONFLICT(id) DO NOTHING',[...row.slice(0,6),JSON.stringify(row[6]),row[7]]);for(const row of tariffs)await client.query("INSERT INTO tariffs(id,name,slug,eyebrow,description,price_mode,features,cta,sort_order,is_visible) VALUES($1,$2,$3,$4,$5,$6,$7,'Обсудить проект',$8,true) ON CONFLICT(id) DO NOTHING",[...row.slice(0,6),JSON.stringify(row[6]),row[7]]);await client.query("INSERT INTO projects(id,title,slug,subtitle,short_description,status,published,featured,featured_order,service_tags) VALUES('project-fasadof','ФАСАДОФ','fasadof','Цифровая инфраструктура для бизнеса фасадов и столешниц.','Цифровая инфраструктура для бизнеса фасадов и столешниц.','IN_PROGRESS',true,true,1,$1) ON CONFLICT(id) DO NOTHING",[JSON.stringify(['Strategy','Design','Development','Infrastructure'])]);for(let i=0;i<system.length;i++){const [title,shortText,detailText]=system[i];await client.query("INSERT INTO project_blocks(id,project_id,type,data,sort_order,visible) VALUES($1,'project-fasadof','SYSTEM_ITEM',$2,$3,true) ON CONFLICT(id) DO NOTHING",[`fasadof-system-${title.toLowerCase()}`,JSON.stringify({number:String(i+1).padStart(2,'0'),title,shortText,detailText}),i+1])}await client.query("INSERT INTO settings(key,value) VALUES('weather_city','Воронеж') ON CONFLICT(key) DO NOTHING");await client.query("INSERT INTO roles(id,name,permissions,is_system) VALUES('role-owner','Владелец',$1,true) ON CONFLICT(id) DO NOTHING",[JSON.stringify(['*'])]);if(process.env.ADMIN_EMAIL&&process.env.ADMIN_PASSWORD_HASH)await client.query("INSERT INTO users(id,email,name,password_hash,role_id,active) VALUES('user-owner',lower($1),'Владелец',$2,'role-owner',true) ON CONFLICT(id) DO NOTHING",[process.env.ADMIN_EMAIL,process.env.ADMIN_PASSWORD_HASH]);await client.query('COMMIT');console.log('PostgreSQL seed complete.')}catch(error){await client.query('ROLLBACK');throw error}finally{client.release();await pool.end()}
